apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
  namespace: knative-serving
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: purpose
                operator: In
                values:
                - control
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: control

